In [8]:
import pandas as pd
from io import StringIO
csv_data = '''A,B,C,D
            1.0,2.0,3.0,4.0
            5.0,6.0,,8.0
            10.0,11.0,12.0,'''
df= pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [5]:
df.isnull().sum

<bound method DataFrame.sum of        A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True>

In [13]:
df.dropna(how='all')
#df.dropna(thresh=4)
df.dropna(subset=['C'])

A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

In [14]:
from sklearn.impute import SimpleImputer
import numpy as np
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

moving to categorical data

In [15]:
del df

In [27]:
df = pd.DataFrame([
                ['green', 'M', 10.1,'class2'],
                ['red', 'L', 13.5,'class1'],
                ['blue', 'XL', 15.3,'class2']])
df.columns=['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [ ]:
size_mapping = {'XL':3, 'L':2, 'M':1}
df['size'] = df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [29]:
inv_size_mapping = {v:k for k,v in size_mapping.items()}
df['size'].astype(int).map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object

In [30]:
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}
class_mapping

{'class1': 0, 'class2': 1}

In [31]:
df['classlabel'] = df['classlabel'].map(class_mapping)
df

color  size  price  classlabel
0  green     1   10.1           1
1    red     2   13.5           0
2   blue     3   15.3           1

In [32]:
from sklearn.preprocessing import LabelEncoder
X = df[['color', 'size' ,'price']].values
color_le = LabelEncoder()
X[:,0] = color_le.fit_transform(X[:,0])
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [34]:
del X

NameError: name 'X' is not defined

In [35]:
from sklearn.preprocessing import OneHotEncoder
X = df[['color', 'size', 'price']].values
color_ohe = OneHotEncoder()
color_ohe.fit_transform(X[:,0].reshape(-1,1)).toarray()


array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [36]:
pd.get_dummies(df[['color', 'size' ,'price']])

size  price  color_blue  color_green  color_red
0     1   10.1       False         True      False
1     2   13.5       False        False       True
2     3   15.3        True        False      False